spring.application.name=marchepublic
spring.datasource.url=jdbc:postgresql://localhost:5432/marchepublic
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

scraper.marches-publics.default-url=https://www.marchespublics.gov.ma
scraper.marches-publics.advanced-search-url=https://www.marchespublics.gov.ma/index.php?page=entreprise.EntrepriseAdvancedSearch&searchAnnCons
scraper.marches-publics.timeout-ms=15000