spring.application.name=marchepublic
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/marchepublic}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

scraper.marches-publics.default-url=https://www.marchespublics.gov.ma
scraper.marches-publics.advanced-search-url=https://www.marchespublics.gov.ma/index.php?page=entreprise.EntrepriseAdvancedSearch&searchAnnCons
scraper.marches-publics.excluded-companies-url=https://www.marchespublics.gov.ma/index.php?page=entreprise.EntrepriseRechercherSocietesExclues&search=1
scraper.cncp.url=https://www.sgg.gov.ma/Commissionnationaledelacommandepublique.aspx
scraper.marches-publics.timeout-ms=15000

scraper.selenium.enabled=true
scraper.selenium.headless=true
scraper.selenium.implicit-wait-seconds=0
scraper.selenium.page-load-timeout-seconds=30
scraper.selenium.script-timeout-seconds=30